-- Seeker Of SoundZ v7.0.48 — Site Content Studio storage repair
-- Run once in Supabase Dashboard > SQL Editor (safe to re-run).
-- Preserves existing rows; does not truncate or drop the content table.

create table if not exists public.site_content_overrides (
  id bigint generated by default as identity primary key,
  page_slug text not null,
  content_key text not null,
  content_html text,
  is_hidden boolean not null default false,
  updated_at timestamptz not null default now(),
  updated_by uuid default auth.uid(),
  unique (page_slug, content_key)
);

alter table public.site_content_overrides
  add column if not exists style_json jsonb not null default '{}'::jsonb;

-- Keep existing installations compatible if the table was created partially.
alter table public.site_content_overrides
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists updated_by uuid default auth.uid();

-- An upsert must have a unique index/constraint on the conflict columns.
create unique index if not exists site_content_overrides_page_key_uq
  on public.site_content_overrides (page_slug, content_key);

-- Only signed-in Owner/Administrator members may modify public content.
-- The site already uses public.profiles.role for these roles.
create or replace function public.sos_can_edit_site_content()
returns boolean
language sql stable security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.profiles p
    where p.id = (select auth.uid())
      and p.role::text in ('owner', 'administrator')
  );
$$;
revoke all on function public.sos_can_edit_site_content() from public;
grant execute on function public.sos_can_edit_site_content() to authenticated;

alter table public.site_content_overrides enable row level security;

-- Replace legacy policies that incorrectly allowed ANY signed-in user to edit.
drop policy if exists "authenticated can manage site content" on public.site_content_overrides;
drop policy if exists "public can read site content" on public.site_content_overrides;
drop policy if exists "SOS public site content read" on public.site_content_overrides;
drop policy if exists "SOS admin site content insert" on public.site_content_overrides;
drop policy if exists "SOS admin site content update" on public.site_content_overrides;
drop policy if exists "SOS admin site content delete" on public.site_content_overrides;

create policy "SOS public site content read"
  on public.site_content_overrides for select to anon, authenticated
  using (true);
create policy "SOS admin site content insert"
  on public.site_content_overrides for insert to authenticated
  with check (public.sos_can_edit_site_content());
create policy "SOS admin site content update"
  on public.site_content_overrides for update to authenticated
  using (public.sos_can_edit_site_content())
  with check (public.sos_can_edit_site_content());
create policy "SOS admin site content delete"
  on public.site_content_overrides for delete to authenticated
  using (public.sos_can_edit_site_content());

grant usage on schema public to anon, authenticated;
grant select on public.site_content_overrides to anon;
grant select, insert, update, delete on public.site_content_overrides to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- Confirm required fields exist (a result row means the migration ran).
select column_name, data_type
from information_schema.columns
where table_schema='public' and table_name='site_content_overrides'
  and column_name in ('page_slug','content_key','content_html','style_json','is_hidden','updated_at','updated_by')
order by column_name;
