-- Seeker Of SoundZ v7.0.19 — Site Image Studio
create table if not exists public.site_image_overrides (
 id bigint generated by default as identity primary key,
 page_slug text not null,
 image_key text not null,
 image_url text,
 alt_text text not null default '',
 is_hidden boolean not null default false,
 updated_at timestamptz not null default now(),
 updated_by uuid default auth.uid(),
 unique(page_slug,image_key)
);
alter table public.site_image_overrides enable row level security;
drop policy if exists "public can read site images" on public.site_image_overrides;
create policy "public can read site images" on public.site_image_overrides for select using (true);
drop policy if exists "authenticated can manage site images" on public.site_image_overrides;
create policy "authenticated can manage site images" on public.site_image_overrides for all to authenticated using (true) with check (true);
grant select on public.site_image_overrides to anon, authenticated;
grant insert, update, delete on public.site_image_overrides to authenticated;
