-- Seeker Of SoundZ v7.0.17 Site Content Studio
create table if not exists public.site_content_overrides (
 id bigint generated by default as identity primary key, page_slug text not null, content_key text not null, content_html text, is_hidden boolean not null default false, updated_at timestamptz not null default now(), updated_by uuid default auth.uid(), unique(page_slug,content_key)
);
alter table public.site_content_overrides enable row level security;
drop policy if exists "public can read site content" on public.site_content_overrides;
create policy "public can read site content" on public.site_content_overrides for select using (true);
-- Writes require an authenticated account. Existing Admin Hub still performs its Owner/Admin gate before exposing controls.
drop policy if exists "authenticated can manage site content" on public.site_content_overrides;
create policy "authenticated can manage site content" on public.site_content_overrides for all to authenticated using (true) with check (true);
