(()=>{'use strict';
const panel=document.getElementById('adminPanel'),menu=document.querySelector('.adminMenu');if(!panel||!menu)return;
const client=window.SOS_SUPABASE?.client,fonts={sphere:'Sphere Fez (current)',system:'Clean System / Inter',condensed:'Condensed Sans',classic:'Classic Serif',mono:'Monospace'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const opts=v=>Object.entries(fonts).map(([k,n])=>`<option value="${k}" ${k===v?'selected':''}>${n}</option>`).join('');
function add(){if(menu.querySelector('[data-panel="typography"]'))return;const b=document.createElement('button');b.dataset.panel='typography';b.textContent='Typography Studio';const social=menu.querySelector('[data-panel="socials"]');(social||menu.lastElementChild)?.insertAdjacentElement('afterend',b)}
async function get(){let s={display:'sphere',heading:'sphere',card:'sphere',body:'system'};try{Object.assign(s,JSON.parse(localStorage.getItem('sos_typography_v709')||'{}'))}catch{};if(client){try{const {data}=await client.rpc('admin_get_site_typography');if(data)Object.assign(s,data)}catch{}}return s}
async function render(){const s=await get();panel.innerHTML=`<div class="adminSectionHead"><div><p class="sectionEyebrow">Site Typography</p><h2>Typography Studio</h2></div><span class="statusPill">Safe Font Controls</span></div><p class="adminLead">Choose fonts by text role instead of forcing one font everywhere. The containment rules stay active so new titles and descriptions remain inside their cards.</p><form id="typographyFormV709" class="appForm adminEditor"><div class="formRow"><label>Large display text<select name="display">${opts(s.display)}</select></label><label>Section headings<select name="heading">${opts(s.heading)}</select></label></div><div class="formRow"><label>Card & module titles<select name="card">${opts(s.card)}</select></label><label>Paragraph / description text<select name="body">${opts(s.body)}</select></label></div><div class="typographyPreviewV709"><p class="sectionEyebrow">Live preview</p><h2 data-type-preview>Seeker Of SoundZ</h2><h3 data-card-preview>Frequency Unknown</h3><p data-body-preview>New text added through the Admin Hub will remain readable and contained inside the current layout.</p></div><button class="primaryButton" type="submit">Publish Typography</button><p class="formMessage" data-type-message></p></form>`;bindPreview()}
function bindPreview(){const f=panel.querySelector('#typographyFormV709');if(!f)return;const update=()=>{const v=Object.fromEntries(new FormData(f));window.SOSTypography?.apply(v);f.querySelector('[data-type-preview]').style.fontFamily=window.SOSTypography?.fonts[v.heading]||'';f.querySelector('[data-card-preview]').style.fontFamily=window.SOSTypography?.fonts[v.card]||'';f.querySelector('[data-body-preview]').style.fontFamily=window.SOSTypography?.fonts[v.body]||''};f.querySelectorAll('select').forEach(x=>x.addEventListener('change',update));update()}
menu.addEventListener('click',e=>{const b=e.target.closest('[data-panel="typography"]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();menu.querySelectorAll('[data-panel]').forEach(x=>x.classList.toggle('active',x===b));render()},true);
panel.addEventListener('submit',async e=>{const f=e.target.closest('#typographyFormV709');if(!f)return;e.preventDefault();const s=Object.fromEntries(new FormData(f)),m=f.querySelector('[data-type-message]');localStorage.setItem('sos_typography_v709',JSON.stringify(s));window.SOSTypography?.apply(s);m.textContent='Saving…';if(client){const {error}=await client.rpc('admin_save_site_typography',{p_settings:s});if(error){m.textContent='Saved in this browser. Supabase setup is still needed: '+error.message;return}}m.textContent='Typography published successfully.'});
add();
})();
