(()=>{'use strict';
const groups=[
 ['Dashboard',['overview']],['Website',['pageaccess','sitecontent','typography']],['Media & Galleries',['siteimages','gallery','videos','music']],['Community',['messages','members','forums','announcements','events','collaborations']],['Commerce',['catalog']],['Brand & Settings',['socials','performance','settings']],['Help',['tutorials']]
];
const tutorials={
 overview:['Admin Overview','Use this dashboard to check site status and jump into management tools. Nothing is published until you use the save/publish action in a manager.'],
 pageaccess:['Page Access & Visibility','Choose who can open each page. Public is visible to everyone; restricted pages are removed from navigation for users without permission. Save the page rule and confirm the success toast.'],
 sitecontent:['Site Content + Typography','Choose a page, load its editable blocks, change the text, then adjust font, size, weight, or letter spacing for that exact block. Save publishes the override through Supabase; Reset All restores the original file content and type.'],
 typography:['Global Typography','Use this for site-wide font roles. Use Site Content Studio when only one heading or paragraph needs a different size or type treatment.'],
 siteimages:['Site Images','Choose a page to find its managed images. Replace the source/URL, edit alt text, hide/show, or reset an image.'],
 gallery:['Gallery Manager','Load the live gallery first, then create, edit, reorder, hide, or remove gallery entries. Publish/sync when finished so the public Gallery receives the changes.'],
 videos:['Video Manager','Manage public video entries and featured video assignments. Keep titles, thumbnails, and destination links accurate before publishing.'],
 music:['Music Manager','Create and edit releases, audio links, cover art, and featured music. Preview links before publishing.'],
 members:['Members','Review member accounts and roles. Only grant elevated roles to people who should have administrative or private-page access.'],
 forums:['Forum Moderation','Review community posts and moderation tools. Use moderation actions only on the intended post/member.'],
 collaborations:['Collaboration Teams','Manage collaboration access and teams. The Collaboration Studio remains the workspace for messages, notes, audio versions, and project progress.'],
 socials:['Socials Manager','Edit public social links from one place. Save and verify each destination after publishing.'],
 performance:['Performance & Storage','Review storage/performance information and maintenance tools. Avoid clearing stored data unless you know it is safe to remove.'],
 settings:['Settings','Use this for site-level administration settings. Change one setting at a time and verify the public site afterward.']
};
function addTutorialButton(menu){let b=menu.querySelector('[data-panel="tutorials"]');if(b)return b;b=document.createElement('button');b.dataset.panel='tutorials';b.textContent='Tutorial Center';menu.insertBefore(b,menu.querySelector('.adminMenuLink'));return b}
function organize(){const menu=document.querySelector('.adminMenu');if(!menu)return;addTutorialButton(menu);menu.querySelectorAll('.adminMenuGroupTitleV722').forEach(x=>x.remove());groups.forEach(([name,ids])=>{const els=ids.map(id=>menu.querySelector(`[data-panel="${id}"]`)).filter(Boolean);if(!els.length)return;const title=document.createElement('div');title.className='adminMenuGroupTitleV722';title.textContent=name;els[0].before(title);els.forEach(el=>{el.classList.add('adminMenuGroupedV722');title.parentNode.insertBefore(el,title.nextSibling);title.after(el)})});const link=menu.querySelector('.adminMenuLink');if(link){link.classList.add('adminMenuCollabV722');menu.append(link)}}
function renderTutorials(){const panel=document.getElementById('adminPanel');if(!panel)return;panel.innerHTML=`<div class="adminTutorialCenterV722"><div class="adminSectionHead"><div><p class="sectionEyebrow">Admin Help</p><h2>Tutorial Center</h2><p>Choose a section for a focused guide to that part of the Admin Hub.</p></div><span class="statusPill">Built-in Help</span></div><div class="tutorialLayoutV722"><nav class="tutorialNavV722">${Object.entries(tutorials).map(([k,v])=>`<button data-tutorial="${k}">${v[0]}</button>`).join('')}</nav><article id="tutorialBodyV722" class="tutorialBodyV722"><p class="sectionEyebrow">Start here</p><h3>Choose a tutorial</h3><p>Select a section on the left. Each guide explains what that admin tool controls and the safest way to publish changes.</p></article></div></div>`;panel.querySelectorAll('[data-tutorial]').forEach(b=>b.onclick=()=>{panel.querySelectorAll('[data-tutorial]').forEach(x=>x.classList.toggle('active',x===b));const [title,body]=tutorials[b.dataset.tutorial];panel.querySelector('#tutorialBodyV722').innerHTML=`<p class="sectionEyebrow">Section Tutorial</p><h3>${title}</h3><p>${body}</p><div class="tutorialStepsV722"><strong>Safe workflow</strong><ol><li>Open the matching Admin Hub section.</li><li>Make one focused change and review the fields.</li><li>Press Save/Publish and wait for the confirmation toast.</li><li>Open the public page in a new tab and verify the result.</li></ol></div>`})}
function bind(){const menu=document.querySelector('.adminMenu');if(!menu)return;menu.addEventListener('click',e=>{const b=e.target.closest('[data-panel="tutorials"]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();menu.querySelectorAll('[data-panel]').forEach(x=>x.classList.toggle('active',x===b));renderTutorials()},true);organize();let n=0;const t=setInterval(()=>{organize();if(++n>35)clearInterval(t)},120)}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',bind):bind()})();
