(()=>{'use strict';
const PAGES=[['Home','index.html'],['About','about.html'],['Music','music.html'],['Plugins','producer-hub.html'],['Gallery','gallery.html'],['Videos','videos.html'],['Merch','merch.html'],['Forums','forums.html'],['Events','events.html'],['Socials','socials.html'],['Contact','contact.html'],['Latest Updates','latest-updates.html'],['Collaboration','collaboration.html']];
const MODES=[['public','Public — everyone'],['members','Members — signed in'],['vip','VIP / Premium members'],['collaboration','Collaboration approved'],['admin','Admins only'],['hidden','Hidden — admins only']];
async function client(){for(let i=0;i<50;i++){const c=window.SOS_SUPABASE?.client||window.SOSSupabase?.client||window.supabaseClient;if(c?.from)return c;await new Promise(r=>setTimeout(r,80))}return null}
function toast(msg,title='Page Access'){window.SOS?.toast?.(msg,{title,icon:'✓',duration:4200})}
function mount(){const menu=document.querySelector('.adminMenu');if(!menu||menu.querySelector('[data-panel="pageaccess"]'))return;const b=document.createElement('button');b.dataset.panel='pageaccess';b.textContent='Page Access & Visibility';b.className='adminNewFeatureV720';const overview=menu.querySelector('[data-panel="overview"]');overview?.insertAdjacentElement('afterend',b);b.onclick=()=>{menu.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));render()}}
async function render(){const panel=document.getElementById('adminPanel');panel.innerHTML=`<div class="adminSectionHead"><div><p class="sectionEyebrow">Navigation + Page Security</p><h2>Page Access & Visibility</h2></div></div><p class="adminLead">Choose who can see each public page. Restricted pages are also removed from navigation for visitors who do not have access.</p><div id="paStatus" class="contentStudioStatus">Loading access rules…</div><div id="paGrid" class="pageAccessGrid721"></div>`;const c=await client(),grid=panel.querySelector('#paGrid'),status=panel.querySelector('#paStatus');if(!c){status.textContent='Supabase is unavailable.';return}const {data,error}=await c.from('site_page_access').select('*');if(error){status.textContent='Could not load rules: '+error.message;return}const map=new Map((data||[]).map(x=>[x.page_slug,x.access_mode]));grid.innerHTML=PAGES.map(([label,slug])=>`<article class="pageAccessCard721"><div><strong>${label}</strong><small>${slug}</small></div><select data-page="${slug}">${MODES.map(([v,l])=>`<option value="${v}" ${(map.get(slug)||'public')===v?'selected':''}>${l}</option>`).join('')}</select><button type="button" data-save-page="${slug}">Save</button></article>`).join('');status.textContent='Access rules loaded. Changes apply to the page and navigation after saving.';grid.onclick=async e=>{const btn=e.target.closest('[data-save-page]');if(!btn)return;const slug=btn.dataset.savePage,sel=grid.querySelector(`[data-page="${slug}"]`),mode=sel.value;btn.disabled=true;const {data:{user}}=await c.auth.getUser();const {error}=await c.from('site_page_access').upsert({page_slug:slug,access_mode:mode,updated_at:new Date().toISOString(),updated_by:user?.id||null},{onConflict:'page_slug'});btn.disabled=false;if(error){status.textContent='Save failed: '+error.message;window.SOS?.toast?.(error.message,{title:'Save failed'});return}status.textContent=`Saved ${slug}: ${MODES.find(x=>x[0]===mode)?.[1]}.`;toast(`${labelFor(slug)} access saved. Navigation visibility will update automatically.`,'Page access saved')}}
function labelFor(slug){return PAGES.find(x=>x[1]===slug)?.[0]||slug}
function init(){mount();let n=0,t=setInterval(()=>{mount();if(++n>30)clearInterval(t)},100)}document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();
