(()=>{'use strict';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const client=()=>window.SOS_SUPABASE?.client, table='sos_bug_reports',bucket='sos-bug-screenshots';
let items=[],limit=15,admin=false,seen=null;
const statuses={not_started:'Not Worked On',pending:'Pending',in_progress:'In Progress',finished:'Finished'};
function badge(x){return `<span class="bug62Status" data-status="${esc(x)}">${statuses[x]||statuses.not_started}</span>`}
function date(x){return new Date(x).toLocaleString()}
function screenshots(x){return (x.screenshots||[]).map(u=>{const safe=String(u);return /^https:\/\//.test(safe)?`<a href="${esc(safe)}" target="_blank" rel="noopener"><img loading="lazy" src="${esc(safe)}" alt="Attached screenshot"></a>`:''}).join('')}
function ticket(x,isAdmin=false){const archived=x.status==='finished';return `<article class="bug62Ticket" data-archived="${archived}"><div>${badge(x.status)} <small>#guest${x.id} · ${esc(x.page_name)} · ${date(x.created_at)}</small></div><h3>${esc(x.subject)}</h3><div class="bug62Detail"><p>${esc(x.description)}</p><div class="bug62Thumbs">${screenshots(x)}</div>${x.admin_note?`<p><strong>Admin update:</strong> ${esc(x.admin_note)}</p>`:''}</div>${archived?'<button type="button" class="secondaryButton" data-expand-bug>Show archived details</button>':''}${isAdmin?`<div class="bug62AdminActions"><select aria-label="Report status" data-bug-status="${x.id}">${Object.entries(statuses).map(([k,v])=>`<option value="${k}" ${x.status===k?'selected':''}>${v}</option>`).join('')}</select><button data-bug-edit="${x.id}">Edit</button><button data-bug-hide="${x.id}">${x.hidden?'Unhide':'Hide'}</button><button data-bug-delete="${x.id}">Delete</button></div>`:''}</article>`}
async function load(){const c=client();if(!c)return;const q=await c.from(table).select('*').order('created_at',{ascending:$('#bug62Sort')?.value==='old'}).limit(200);if(q.error){if($('#bug62Reports'))$('#bug62Reports').textContent='Could not load reports: '+q.error.message;return}items=q.data||[];render()}
function render(){const target=$('#bug62Reports');if(!target)return;const visible=items.slice(0,limit);target.innerHTML=visible.map(x=>ticket(x)).join('')||'<p>No reports yet. Be the first to submit one.</p>';if($('#bug62More'))$('#bug62More').hidden=items.length<=limit}
function msg(t){if($('#bug62Feedback'))$('#bug62Feedback').textContent=t}
async function submit(e){e.preventDefault();const c=client();if(!c)return msg('Supabase is unavailable. Try again shortly.');const f=e.currentTarget,button=$('#bug62Submit');button.disabled=true;msg('Submitting report…');try{const fd=new FormData(f);const page=fd.get('page')==='Other / Custom'?String(fd.get('custom_page')||'').trim():String(fd.get('page'));if(!page)throw Error('Please enter a custom page or issue.');const files=[...($('#bug62Files')?.files||[])];if(files.length>3)throw Error('Please upload no more than 3 screenshots.');const urls=[];for(const file of files){if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>5*1024*1024)throw Error('Screenshots must be PNG, JPG or WebP under 5 MB.');const name='reports/'+crypto.randomUUID()+'.'+({ 'image/png':'png','image/jpeg':'jpg','image/webp':'webp'}[file.type]);const up=await c.storage.from(bucket).upload(name,file,{contentType:file.type,upsert:false});if(up.error)throw up.error;urls.push(c.storage.from(bucket).getPublicUrl(name).data.publicUrl)}const q=await c.from(table).insert({subject:String(fd.get('subject')).trim(),page_name:page,description:String(fd.get('description')).trim(),screenshots:urls}).select('id').single();if(q.error)throw q.error;f.reset();$('#bug62CustomWrap').hidden=true;msg(`Report submitted successfully as #guest${q.data.id}. Thank you!`);await load()}catch(err){msg('Could not submit: '+err.message)}finally{button.disabled=false}}
function toast(message){if(document.querySelector('.bug62Toast'))return;const el=document.createElement('div');el.className='bug62Toast';el.setAttribute('role','status');el.textContent=message;document.body.append(el);setTimeout(()=>el.remove(),7000)}
async function checkAdmin(){const c=client();if(!c)return false;const user=await c.auth.getUser();if(!user.data?.user)return false;const q=await c.rpc('is_admin');admin=q.data===true&&!q.error;return admin}
async function loadAdmin(){if(!admin)return;const target=$('#bug62AdminInbox');if(!target)return;const q=await client().from(table).select('*').order('created_at',{ascending:false}).limit(100);if(q.error){target.textContent='Bug reports unavailable: '+q.error.message;return}const list=q.data||[];target.innerHTML=`<div class="adminSectionHead"><div><p class="sectionEyebrow">Community Support</p><h2>Bug Reports</h2></div><span class="statusPill">${list.filter(x=>x.status==='not_started').length} not started</span></div><div class="bug62AdminActions"><label>Sort <select id="bug62AdminSort"><option value="new">Newest first</option><option value="old">Oldest first</option></select></label></div><div id="bug62AdminList">${list.map(x=>ticket(x,true)).join('')||'<p>No bug reports yet.</p>'}</div>`;$('#bug62AdminSort').onchange=e=>{$('#bug62AdminList').innerHTML=(e.target.value==='old'?[...list].reverse():list).map(x=>ticket(x,true)).join('')};const latest=list[0]?.id||0;if(seen!==null&&latest>seen)toast('New bug report received — open Contact Inbox to review.');seen=Math.max(seen||0,latest)}
function mountAdmin(){const panel=$('#adminPanel');if(!panel||!admin)return;const heading=[...panel.querySelectorAll('h2')].find(x=>x.textContent.trim()==='Collaboration Requests');if(!heading)return;const cards=heading.closest('.adminSectionHead')?.nextElementSibling;if(!cards)return;if($('#bug62AdminInbox'))return;const section=document.createElement('section');section.id='bug62AdminInbox';section.className='bug62Admin';cards.after(section);loadAdmin()}
async function change(id,patch){const q=await client().from(table).update({...patch,updated_at:new Date().toISOString(),...(patch.status==='finished'?{finished_at:new Date().toISOString()}:patch.status?{finished_at:null}:{})}).eq('id',id);if(q.error)throw q.error;await loadAdmin()}
async function action(e){let b=e.target.closest('[data-expand-bug]');if(b){const card=b.closest('.bug62Ticket');card.dataset.archived='false';b.remove();return}b=e.target.closest('[data-bug-edit],[data-bug-hide],[data-bug-delete]');if(!b||!admin)return;const id=Number(b.dataset.bugEdit||b.dataset.bugHide||b.dataset.bugDelete);try{if(b.hasAttribute('data-bug-delete')){if(!confirm('Permanently delete this report?'))return;const q=await client().from(table).delete().eq('id',id);if(q.error)throw q.error;return loadAdmin()}if(b.hasAttribute('data-bug-hide')){const hidden=b.textContent==='Hide';return change(id,{hidden})}const article=b.closest('.bug62Ticket'),subject=prompt('Edit report subject',article.querySelector('h3')?.textContent||'');if(subject===null)return;const note=prompt('Admin note (shown publicly)',article.querySelector('.bug62Detail strong')?.parentElement?.textContent?.replace('Admin update:','').trim()||'');if(note===null)return;return change(id,{subject:subject.trim(),admin_note:note.trim()})}catch(err){toast('Update failed: '+err.message)}}
function init(){if($('#bug62Form')){$('#bug62Form').addEventListener('submit',submit);$('#bug62Page').addEventListener('change',e=>{$('#bug62CustomWrap').hidden=e.target.value!=='Other / Custom'});$('#bug62Sort').addEventListener('change',load);$('#bug62More').addEventListener('click',()=>{limit+=15;render()});load()}document.addEventListener('click',action);if($('#adminPanel'))checkAdmin().then(ok=>{if(!ok)return;mountAdmin();new MutationObserver(()=>{if(!$('#bug62AdminInbox'))mountAdmin()}).observe($('#adminPanel'),{childList:true});setInterval(async()=>{const q=await client().from(table).select('id').order('id',{ascending:false}).limit(1);if(!q.error&&q.data?.[0]?.id>seen){toast('New bug report submitted.');seen=q.data[0].id;if($('#bug62AdminInbox'))loadAdmin()}},60000)});document.addEventListener('change',async e=>{const s=e.target.closest('[data-bug-status]');if(!s||!admin)return;try{await change(Number(s.dataset.bugStatus),{status:s.value})}catch(err){toast('Status update failed: '+err.message)}})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
