/* Seeker Of SoundZ v7.0.27 — preview reliability + member personalization */
(()=>{'use strict';
const KEY='sos_member_display_v7027'; const uid=()=>window.SOS?.getSession?.()?.id||'guest';
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}};
const current=()=>({...{textSize:'normal',density:'balanced',shape:'rounded'},...(read()[uid()]||{})});
function apply(v=current()){document.documentElement.dataset.memberTextSize=v.textSize;document.documentElement.dataset.memberProfileDensity=v.density;document.documentElement.dataset.memberProfileShape=v.shape;document.querySelectorAll('.memberAppearanceV7026').forEach(x=>{x.dataset.profileDensity=v.density;x.dataset.profileShape=v.shape})}
function save(v){const a=read();a[uid()]=v;localStorage.setItem(KEY,JSON.stringify(a));apply(v)}
function enhanceProfile(){const box=document.querySelector('.memberAppearanceV7026');if(!box||box.querySelector('.memberAppearanceExtrasV7027'))return;const v=current(),x=document.createElement('div');x.className='memberAppearanceExtrasV7027';x.innerHTML=`<label>Member text size<select data-v7027="textSize"><option value="small">Compact text</option><option value="normal">Balanced</option><option value="large">Large & readable</option></select></label><label>Profile spacing<select data-v7027="density"><option value="compact">Compact</option><option value="balanced">Balanced</option><option value="spacious">Spacious</option></select></label><label>Profile card shape<select data-v7027="shape"><option value="rounded">SOS Rounded</option><option value="soft">Soft Studio</option><option value="square">Precision Square</option></select></label><label>Preview behavior<select data-v7027="preview"><option value="live">Live while editing</option><option value="manual">Manual test only</option></select></label>`;box.appendChild(x);x.querySelectorAll('select').forEach(el=>{el.value=v[el.dataset.v7027]|| (el.dataset.v7027==='preview'?'live':'normal');el.addEventListener('change',()=>{const n=current();x.querySelectorAll('select').forEach(q=>n[q.dataset.v7027]=q.value);save(n);window.SOS?.toast?.('Profile display preference updated.',{title:'Member appearance'})})});apply(v)}
function syncPreview(st){if(!st)return;const get=k=>st.querySelector(`[data-setting="${k}"]`);const p=st.querySelector('[data-loader-profile-preview]');if(p){['loaderProgressStyle','loaderLogoMotion','loaderLogoSpeed','loaderBarAnimation','loaderBrandFont','loaderCenterEffect','loaderBackgroundStyle','loaderBackgroundMotion'].forEach(k=>{const el=get(k);if(el)p.dataset[k.replace(/^loader/,'').replace(/^[A-Z]/,m=>m.toLowerCase())]=el.value});const map={loaderProgressStyle:'progressStyle',loaderLogoMotion:'logoMotion',loaderLogoSpeed:'logoSpeed',loaderBarAnimation:'barAnimation',loaderBrandFont:'brandFont',loaderCenterEffect:'centerEffect',loaderBackgroundStyle:'backgroundStyle',loaderBackgroundMotion:'backgroundMotion'};Object.entries(map).forEach(([k,d])=>{const el=get(k);if(el)p.dataset[d]=el.value});[['loaderShowLogo','hideLogo'],['loaderShowOrbits','hideOrbits'],['loaderShowGlow','hideGlow'],['loaderShowParticles','hideParticles'],['loaderShowBrand','hideBrand'],['loaderShowSubtitle','hideSubtitle'],['loaderShowStatus','hideStatus'],['loaderShowPercent','hidePercent']].forEach(([k,c])=>{const el=get(k);if(el)p.classList.toggle(c,!el.checked)});const sw=get('loaderSwipe');if(sw)p.classList.toggle('showSwipe',sw.checked)}const live=st.querySelector('[data-experience-live-preview]'),tr=get('transition');if(live&&tr){live.dataset.transition=tr.value;const label=live.querySelector('[data-preview-transition-name]');if(label)label.textContent=tr.options[tr.selectedIndex]?.text||tr.value}}
function playTransition(st){syncPreview(st);const box=st?.querySelector('[data-experience-live-preview]');if(!box)return;box.classList.remove('isPreviewing');void box.offsetWidth;box.classList.add('isPreviewing');clearTimeout(box._v7027);box._v7027=setTimeout(()=>box.classList.remove('isPreviewing'),box.dataset.transition==='minimal'?550:1700)}
document.addEventListener('input',e=>{const st=e.target.closest?.('[data-experience-studio]');if(st)syncPreview(st)});document.addEventListener('change',e=>{const st=e.target.closest?.('[data-experience-studio]');if(st){syncPreview(st);if(e.target.dataset.setting==='transition')playTransition(st)}});document.addEventListener('click',e=>{const b=e.target.closest?.('[data-experience-preview]');if(b){e.preventDefault();e.stopImmediatePropagation();playTransition(b.closest('[data-experience-studio]'))}},true);
const mo=new MutationObserver(()=>{enhanceProfile();document.querySelectorAll('[data-experience-studio]').forEach(syncPreview)});mo.observe(document.documentElement,{subtree:true,childList:true});document.readyState==='loading'?document.addEventListener('DOMContentLoaded',()=>{enhanceProfile();apply()},{once:true}):(enhanceProfile(),apply());window.addEventListener('sos:supabase-session',()=>setTimeout(()=>{enhanceProfile();apply()},60));
})();
