/* v7.0.36: one deterministic font resolver, without observers or auth mutations. */
(()=>{'use strict';
const KEY='sos_member_font_v7026';
const faces={original:null,system:'system-ui, sans-serif',rounded:'"Trebuchet MS", sans-serif',clean:'Arial, sans-serif',humanist:'Verdana, sans-serif',classic:'Georgia, serif',mono:'Consolas, monospace',retro:'"Courier New", monospace',cowboy:'Rockwell, Georgia, serif',western:'Copperplate, Georgia, serif',arcade:'"Lucida Console", monospace',cinema:'Impact, sans-serif',editorial:'Palatino, Georgia, serif',tech:'"Arial Narrow", sans-serif',grunge:'"SOS Eroded", serif',stencil:'Impact, sans-serif',gothic:'"SOS Malegroth", serif',handwritten:'"SOS Cartoonish", cursive',disco:'"SOS Brigold", serif',scifi:'"SOS Scientific", sans-serif',punk:'"SOS Metalico", sans-serif',minimalist:'Arial, sans-serif',typewriter:'"Courier New", monospace',brigold:'"SOS Brigold", serif',scientific:'"SOS Scientific", sans-serif',metalico:'"SOS Metalico", sans-serif',retrobyte:'"SOS RetroByte", monospace',eroded:'"SOS Eroded", serif',malegroth:'"SOS Malegroth", serif',cartoonish:'"SOS Cartoonish", cursive',godfather:'"SOS Godfather", serif',nonfiction:'"SOS Nonfiction", serif'};
const root=document.documentElement;
function sessionId(){try{return window.SOS?.getSession?.()?.id||null}catch{return null}}
function stored(){try{const id=sessionId();return id?(JSON.parse(localStorage.getItem(KEY)||'{}')[id]||'original'):'original'}catch{return 'original'}}
function apply(value){const key=Object.hasOwn(faces,value)?value:'original';if(key==='original'){root.removeAttribute('data-member-font');root.style.removeProperty('--sos-active-font')}else{root.dataset.memberFont=key;root.style.setProperty('--sos-active-font',faces[key])}const navKey=(()=>{try{const id=sessionId();const obj=JSON.parse(localStorage.getItem('sos_member_style_v7033')||'{}');return (id&&obj[id]?.navFont)||'inherit'}catch{return 'inherit'}})();root.style.setProperty('--sos-active-nav-font',navKey==='inherit'?(faces[key]||'inherit'):(faces[navKey]||faces[key]||'inherit'));const preview=document.querySelector('[data-member-font-preview]');if(preview)preview.style.fontFamily=faces[key]||'';return key}
function sync(){const select=document.querySelector('[data-member-font-select]');const v=stored();if(select&&select.value!==v&&[...select.options].some(o=>o.value===v))select.value=v;apply(v)}
document.addEventListener('change',e=>{if(e.target.matches?.('[data-member-font-select]'))apply(e.target.value);if(e.target.matches?.('[data-member-nav-font]')){const v=e.target.value;root.style.setProperty('--sos-active-nav-font',v==='inherit'?(faces[root.dataset.memberFont]||'inherit'):(faces[v]||'inherit'))}},true);
document.addEventListener('click',e=>{if(e.target.closest?.('[data-member-font-reset]'))apply('original');if(e.target.closest?.('[data-member-font-save]')){const sel=document.querySelector('[data-member-font-select]');if(sel)apply(sel.value)}},true);
document.addEventListener('DOMContentLoaded',sync,{once:true});window.addEventListener('sos:supabase-session',sync);window.addEventListener('storage',e=>{if(e.key===KEY)sync()});window.SOSMemberFontV7036={apply,sync};
})();
