(()=>{'use strict';
const root=document.documentElement, MIN=50,MAX=250,DEFAULT={text:100,nav:100};
let draft={...DEFAULT},dirty=false,loadedUser=null,client=null,authHooked=false;
const clamp=v=>Math.max(MIN,Math.min(MAX,Math.round(Number(v)||100)));
const status=s=>{const el=document.getElementById('sos42-status');if(el)el.textContent=s};
function apply(){root.style.setProperty('--sos-text-scale',String(draft.text/100));root.style.setProperty('--sos-nav-scale',String(draft.nav/100));root.toggleAttribute('data-sos-text-scaled',draft.text!==100);root.toggleAttribute('data-sos-nav-scaled',draft.nav!==100);for(const k of ['text','nav']){const i=document.getElementById('sos42-'+k),o=document.getElementById('sos42-'+k+'-value');if(i)i.value=draft[k];if(o)o.textContent=draft[k]+'%'}}
function findClient(){const candidates=[window.SOSSupabase?.client,window.supabaseClient,window.sosSupabase,window.SOS?.supabase];return candidates.find(c=>c?.auth?.getUser&&c?.auth?.updateUser)||null}
async function sync(){const c=findClient();if(!c)return;client=c;if(!authHooked&&c.auth.onAuthStateChange){authHooked=true;c.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT'){loadedUser=null;if(!dirty){draft={...DEFAULT};apply()}status('Sign in to save font sizes to your account.')}else if(event==='SIGNED_IN'||event==='USER_UPDATED')setTimeout(()=>sync(),0)})}
try{const {data,error}=await c.auth.getUser();if(error||!data?.user){loadedUser=null;return}const u=data.user;if(dirty)return;if(loadedUser===u.id)return;loadedUser=u.id;const pref=u.user_metadata?.sos_font_sizes;if(pref&&typeof pref==='object'){draft={text:clamp(pref.text),nav:clamp(pref.nav)}}else draft={...DEFAULT};apply();status('Preferences loaded from your Supabase account.')}catch(e){console.warn('SOS font size sync:',e)}}
async function save(){const btn=document.getElementById('sos42-save');const c=findClient();if(!c){status('Supabase is still loading. Please try again.');return}btn.disabled=true;status('Saving to Supabase…');try{const {data:userData,error:userError}=await c.auth.getUser();if(userError||!userData?.user){status('Please sign in to save your font sizes.');return}const values={text:draft.text,nav:draft.nav};const {error}=await c.auth.updateUser({data:{sos_font_sizes:values}});if(error)throw error;dirty=false;loadedUser=userData.user.id;status('Saved to your Supabase account. Your settings will follow you across devices.')}catch(e){status('Could not save: '+(e?.message||'Please retry.'))}finally{btn.disabled=false}}
function mount(){const section=document.querySelector('.memberAppearanceV7026');if(!section)return false;document.querySelectorAll('.memberFontSizeV7039,.memberFontSizeV7038').forEach(el=>el.remove());if(document.getElementById('sos42-size-panel'))return true;const el=document.createElement('section');el.className='memberFontSizeV7039';el.id='sos42-size-panel';el.innerHTML='<h3>Font Size Studio</h3><p>Drag to preview immediately. 100% is the original website size. Save to your Supabase account when ready.</p>'+['text','nav'].map(k=>'<label for="sos42-'+k+'">'+(k==='text'?'Website page text':'Navigation text')+' <output id="sos42-'+k+'-value">100%</output></label><input type="range" id="sos42-'+k+'" min="50" max="250" step="1" value="100" aria-label="'+(k==='text'?'Website page':'Navigation')+' font size"><div class="sos42-marks"><span>50% · Small</span><span>100% · Default</span><span>250% · Large</span></div>').join('')+'<div class="memberFontSizeActionsV7039"><button type="button" class="secondaryButton" id="sos42-save">Save to Supabase</button><button type="button" class="smallAction" id="sos42-reset">Reset to Default</button></div><p id="sos42-status" role="status" aria-live="polite">Sign in to save preferences across devices.</p>';
const actions=section.querySelector('.memberAppearanceActionsV7026');if(actions)actions.before(el);else section.append(el);for(const k of ['text','nav'])el.querySelector('#sos42-'+k).addEventListener('input',e=>{draft[k]=clamp(e.target.value);dirty=true;apply();status('Previewing changes. Press Save to keep them.')});el.querySelector('#sos42-save').addEventListener('click',save);el.querySelector('#sos42-reset').addEventListener('click',()=>{draft={...DEFAULT};dirty=true;apply();status('Default sizes previewed. Press Save to keep them.')});apply();return true}
function start(){apply();if(!mount()){const observer=new MutationObserver(()=>{if(mount())observer.disconnect()});observer.observe(document.body,{childList:true,subtree:true});setTimeout(()=>observer.disconnect(),30000)}sync();let tries=0;const interval=setInterval(()=>{sync();if(++tries>45)clearInterval(interval)},1000);document.addEventListener('sos:supabase-session',()=>sync())}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
