(()=>{'use strict';
const client=()=>window.SOS_SUPABASE?.client;
const KEY='sos_font_size_preferences';let draft={text:100,nav:100},saved={text:100,nav:100},dirty=false,uid=null,loading=false;
const clamp=v=>Math.max(50,Math.min(250,Number(v)||100));
const input=k=>document.getElementById('sos43-'+k);
function apply(){let root=document.documentElement;root.style.setProperty('--sos-text-scale',String(draft.text/100));root.style.setProperty('--sos-nav-scale',String(draft.nav/100));root.toggleAttribute('data-sos-text-scaled',draft.text!==100);root.toggleAttribute('data-sos-nav-scaled',draft.nav!==100);['text','nav'].forEach(k=>{let i=input(k),o=document.getElementById('sos43-'+k+'-value');if(i&&document.activeElement!==i)i.value=draft[k];if(o)o.textContent=draft[k]+'%';if(i)i.style.setProperty('--range-fill',((draft[k]-50)/2)+'%')})}
function status(s){let el=document.getElementById('sos43-status');if(el)el.textContent=s}
async function sync(){if(dirty||loading||!client())return;loading=true;try{const {data:{user},error}=await client().auth.getUser();if(error||!user){uid=null;status('Sign in to save sizes to your Supabase account.');return}if(uid===user.id)return;uid=user.id;let v=user.user_metadata?.[KEY];saved={text:clamp(v?.text??100),nav:clamp(v?.nav??100)};draft={...saved};apply();status('Account font sizes loaded from Supabase.')}catch(e){status('Could not load saved sizes: '+e.message)}finally{loading=false}}
async function save(){let c=client();if(!c){status('Supabase is not configured. Sign in after connecting your backend.');return}let btn=document.getElementById('sos43-save');if(btn)btn.disabled=true;status('Saving to Supabase…');try{let {data:{user},error:authError}=await c.auth.getUser();if(authError||!user)throw Error('Please sign in before saving.');const val={text:draft.text,nav:draft.nav};const {error}=await c.auth.updateUser({data:{[KEY]:val}});if(error)throw error;saved={...val};dirty=false;uid=user.id;status('Saved to your Supabase account. These sizes load when you sign in on another device.')}catch(e){status('Save failed: '+e.message)}finally{if(btn)btn.disabled=false}}
function mount(){let host=document.querySelector('.memberAppearanceV7026');if(!host)return false;document.querySelectorAll('.memberFontSizeV7039,#sos41-size-panel,#sos43-size-panel').forEach(el=>el.remove());let box=document.createElement('section');box.id='sos43-size-panel';box.className='sos43-size-panel';box.innerHTML=`<h3>Custom Font Size Studio</h3><p>Drag either slider to preview your changes instantly. The center is the original 100% size. Save to your Supabase member account when ready.</p><div class="sos43-size-row"><label for="sos43-text">Website Page Text <output id="sos43-text-value">100%</output></label><input id="sos43-text" type="range" min="50" max="250" step="1" value="100"><div class="sos43-markers"><span>50% Small</span><span>100% Default</span><span>250% Large</span></div></div><div class="sos43-size-row"><label for="sos43-nav">Navigation Text <output id="sos43-nav-value">100%</output></label><input id="sos43-nav" type="range" min="50" max="250" step="1" value="100"><div class="sos43-markers"><span>50% Small</span><span>100% Default</span><span>250% Large</span></div></div><div class="sos43-size-actions"><button type="button" id="sos43-save" class="primaryButton">Save Font Sizes to Supabase</button><button type="button" id="sos43-reset" class="smallAction">Reset to 100%</button></div><p id="sos43-status" role="status" aria-live="polite">Move a slider to preview. Save when ready.</p>`;let actions=host.querySelector('.memberAppearanceActionsV7026');if(actions)actions.before(box);else host.append(box);['text','nav'].forEach(k=>input(k).addEventListener('input',e=>{draft[k]=clamp(e.target.value);dirty=true;apply();status('Previewing changes — click Save to keep them across devices.')}));document.getElementById('sos43-save').addEventListener('click',save);document.getElementById('sos43-reset').addEventListener('click',()=>{draft={text:100,nav:100};dirty=true;apply();status('Preview reset to default. Click Save to keep it.')});apply();return true}
function start(){apply();if(!mount()){let obs=new MutationObserver(()=>{if(mount())obs.disconnect()});obs.observe(document.body,{childList:true,subtree:true});setTimeout(()=>obs.disconnect(),30000)}sync();let c=client();if(c)c.auth.onAuthStateChange(()=>{uid=null;setTimeout(sync,0)});document.addEventListener('sos:supabase-session',()=>{uid=null;sync()});window.addEventListener('pageshow',sync)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();