/* Seeker Of SoundZ v7.0.26 — member appearance + progression refresh */
(()=>{'use strict';
const KEY='sos_member_font_v7026';
const uid=()=>window.SOS?.getSession?.()?.id||'guest';
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}};
const get=()=>read()[uid()]||'original';
function apply(v=get()){if(v==='original')document.documentElement.removeAttribute('data-member-font');else document.documentElement.dataset.memberFont=v}
function save(v){const all=read();all[uid()]=v;localStorage.setItem(KEY,JSON.stringify(all));apply(v)}
async function refreshAchievements(showToast=false){const c=window.SOS_SUPABASE?.client;if(!c)return;try{const before=await c.rpc('get_my_achievement_profile');const oldPts=Number(before.data?.points||0);const q=await c.rpc('sync_my_legacy_achievements');if(q.error)throw q.error;const after=await c.rpc('get_my_achievement_profile');const pts=Number(after.data?.points||0);if(showToast&&pts>oldPts)window.SOS?.toast?.(`Achievement progress updated: +${pts-oldPts} points.`,{title:'Progress earned'});window.dispatchEvent(new CustomEvent('sos:achievements-refreshed',{detail:after.data||{}}))}catch(e){console.warn('[SOS progression refresh]',e)}}
function mount(){const form=document.getElementById('publicProfileForm');if(!form||form.querySelector('.memberAppearanceV7026'))return;const box=document.createElement('section');box.className='memberAppearanceV7026';box.innerHTML=`<header><div><p class="sectionEyebrow">Profile Appearance</p><h3>Your reading font</h3><p>Personalize how Seeker Of SoundZ text appears for your signed-in profile. This does not change the site for anyone else.</p></div></header><div class="memberAppearanceGridV7026"><label>Font style<select data-member-font-select><option value="original">Original SOS / Sphere Fez</option><option value="system">Modern System</option><option value="rounded">Rounded Studio</option><option value="clean">Clean Sans</option><option value="humanist">Humanist</option><option value="classic">Classic Serif</option><option value="mono">Producer Mono</option><option value="retro">Retro Terminal</option><option value="cowboy">Cowboy Slab</option><option value="western">Western Poster</option><option value="arcade">Arcade Console</option><option value="cinema">Cinema Condensed</option><option value="editorial">Editorial Classic</option><option value="tech">Tech Narrow</option></select></label><div class="memberFontPreviewV7026" data-member-font-preview>Seeker Of SoundZ — your frequency, your profile.</div></div><div class="memberAppearanceActionsV7026"><button type="button" class="secondaryButton" data-member-font-save>Save Font Preference</button><button type="button" class="smallAction" data-member-font-reset>Use Original Font</button></div>`;const sound=form.querySelector('.profileSoundSettingsV4153');form.insertBefore(box,sound||form.querySelector('button.primaryButton'));const sel=box.querySelector('select');sel.value=get();sel.addEventListener('change',()=>{apply(sel.value);box.querySelector('[data-member-font-preview]').dataset.font=sel.value});box.querySelector('[data-member-font-save]').onclick=()=>{save(sel.value);window.SOS?.toast?.('Your personal font preference was saved.',{title:'Profile appearance'})};box.querySelector('[data-member-font-reset]').onclick=()=>{sel.value='original';save('original');window.SOS?.toast?.('Original Seeker Of SoundZ typography restored.',{title:'Profile appearance'})}}
apply();
let mountTries=0;function safeMount(){mount();if(document.querySelector('.memberAppearanceV7026')||mountTries++>20)return;setTimeout(safeMount,150)}document.readyState==='loading'?document.addEventListener('DOMContentLoaded',safeMount,{once:true}):safeMount();
window.addEventListener('sos:supabase-session',()=>{apply();setTimeout(mount,50)});
window.addEventListener('sos:profile-saved',()=>refreshAchievements(true));
window.SOSMemberExperienceV7026={apply,mount,refreshAchievements};
})();