/* Seeker Of SoundZ v7.0.30 — stable member session/dashboard controller */
(()=>{'use strict';
const body=document.body,auth=document.getElementById('authArea'),dash=document.getElementById('memberDashboard'),logout=document.getElementById('logoutButton');
const client=window.SOS_SUPABASE?.client;let lastId=null, resolving=false;
function resolveShell(session){const signed=!!(session?.id||session?.user?.id);body.classList.remove('membersAuthPendingV4196');body.classList.add('membersAuthResolvedV4196');body.classList.toggle('membersSignedInV4193',signed);if(auth)auth.hidden=signed;if(dash){dash.hidden=!signed;dash.style.removeProperty('display');dash.style.removeProperty('visibility');dash.style.removeProperty('opacity')}return signed}
function hydrate(s){if(!s)return;const avatar=document.getElementById('dashboardAvatar'),name=document.getElementById('dashboardName'),email=document.getElementById('dashboardEmail'),vault=document.getElementById('vaultAccessText');if(avatar)avatar.src=s.avatar||'assets/images/sos-logo.png';if(name)name.textContent=s.displayName||s.username||s.email?.split('@')[0]||'Member';if(email)email.textContent=`${s.email||''}${s.dbRole?` • ${String(s.dbRole).replaceAll('_',' ')}`:''}`;if(vault)vault.textContent=s.dbRole==='premium_member'?'Premium member releases are unlocked for your account.':'Private tracks, videos, and member drops will appear here.'}
function announce(s){resolveShell(s);hydrate(s);if(s?.id!==lastId){lastId=s?.id||null;requestAnimationFrame(()=>{window.SOSMemberExperienceV7026?.mount?.();window.SOSMemberExperienceV7026?.apply?.();window.SOSMemberFontV7028?.apply?.();window.dispatchEvent(new CustomEvent('sos:member-ui-ready',{detail:s||null}))})}}
async function boot(){body.classList.remove('membersAuthPendingV4196');const local=window.SOS?.getSession?.()||null;if(local?.id)announce(local);else resolveShell(null);if(!client)return;try{const result=await Promise.race([client.auth.getSession(),new Promise(r=>setTimeout(()=>r({data:{session:null},timeout:true}),1800))]);const sb=result?.data?.session;if(!sb){if(!local?.id)announce(null);return}if(local?.id===sb.user?.id){announce(local);return}const fallback={id:sb.user.id,email:sb.user.email||'',displayName:sb.user.user_metadata?.display_name||sb.user.user_metadata?.username||sb.user.email?.split('@')[0]||'Member',username:sb.user.user_metadata?.username||'',supabase:true};announce(fallback);const sync=window.SOS_AUTH_BRIDGE?.sync;if(typeof sync==='function'&&!resolving){resolving=true;Promise.race([sync(sb),new Promise(r=>setTimeout(()=>r(fallback),2200))]).then(x=>announce(x||fallback)).catch(()=>announce(fallback)).finally(()=>resolving=false)}}catch(e){console.warn('[Member UI boot]',e);announce(local)}}
if(client){client.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT'){announce(null);return}if(session?.user){const current=window.SOS?.getSession?.();if(current?.id===session.user.id)announce(current);else announce({id:session.user.id,email:session.user.email||'',displayName:session.user.user_metadata?.display_name||session.user.user_metadata?.username||'Member',username:session.user.user_metadata?.username||'',supabase:true})}})}
if(logout){logout.addEventListener('click',async e=>{e.preventDefault();e.stopImmediatePropagation();if(logout.disabled)return;logout.disabled=true;logout.textContent='Signing Out…';try{if(client)await Promise.race([client.auth.signOut({scope:'local'}),new Promise(r=>setTimeout(r,1800))]);try{if(window.SOS?.K?.session)localStorage.removeItem(window.SOS.K.session)}catch{}try{window.SOS?.setSession?.(null)}catch{}window.SOSExperience?.applyDefault?.();announce(null);window.SOS?.toast?.('You have been securely signed out.',{title:'Signed out'});history.replaceState({},'',location.pathname);setTimeout(()=>location.reload(),180)}catch(err){console.error(err);logout.disabled=false;logout.textContent='Sign Out';window.SOS?.toast?.('Sign out could not finish. Please try again.',{title:'Sign-out failed'})}},true)}
window.addEventListener('sos:supabase-session',e=>announce(e.detail));window.addEventListener('sos:session',e=>announce(e.detail));
setTimeout(()=>{body.classList.remove('membersAuthPendingV4196');if(!body.classList.contains('membersAuthResolvedV4196'))resolveShell(window.SOS?.getSession?.()||null)},900);
boot();
})();