(()=>{'use strict';
const KEY='sos_font_size_preferences';const clamp=v=>Math.max(50,Math.min(250,Number(v)||100));
const root=document.documentElement;let draft={text:100,nav:100},saved={text:100,nav:100},dirty=false,userId=null;
const el=id=>document.getElementById('sos44-'+id),client=()=>window.SOS_SUPABASE?.client;
function message(t){if(el('message'))el('message').textContent=t}
function apply(){root.style.setProperty('--sos-text-scale',draft.text/100);root.style.setProperty('--sos-nav-scale',draft.nav/100);root.toggleAttribute('data-sos-text-scaled',draft.text!==100);root.toggleAttribute('data-sos-nav-scaled',draft.nav!==100);for(const [id,k] of [['page','text'],['nav','nav']]){const range=el(id);if(range&&document.activeElement!==range)range.value=draft[k];if(el(id+'-output'))el(id+'-output').textContent=draft[k]+'%';if(range)range.style.setProperty('--fill',((draft[k]-50)/2)+'%')}}
async function load(){const c=client();if(!c||dirty)return;try{const {data,error}=await c.auth.getUser();if(error||!data?.user)return;if(userId===data.user.id)return;userId=data.user.id;const val=data.user.user_metadata?.[KEY];saved={text:clamp(val?.text??100),nav:clamp(val?.nav??100)};draft={...saved};apply();message('Loaded saved font sizes from your Supabase account.')}catch(e){message('Unable to load font sizes: '+e.message)}}
async function save(){const c=client();if(!c){message('Supabase is not connected.');return}const b=el('save');b.disabled=true;message('Saving to Supabase…');try{const {data,error}=await c.auth.getUser();if(error||!data?.user)throw Error('Please sign in to save your font sizes.');const values={text:draft.text,nav:draft.nav};const res=await c.auth.updateUser({data:{[KEY]:values}});if(res.error)throw res.error;saved={...values};dirty=false;userId=data.user.id;message('Saved to Supabase successfully. Your settings will follow your account.')}catch(e){message('Save failed: '+e.message)}finally{b.disabled=false}}
function init(){for(const [id,k] of [['page','text'],['nav','nav']]){el(id)?.addEventListener('input',e=>{draft[k]=clamp(e.target.value);dirty=true;apply();message('Live preview — press Save to keep these values.');});el(id)?.addEventListener('change',e=>{draft[k]=clamp(e.target.value);dirty=true;apply()})}el('save')?.addEventListener('click',save);el('reset')?.addEventListener('click',()=>{draft={text:100,nav:100};dirty=true;apply();message('Reset preview to default. Press Save to store this change.')});apply();load();document.addEventListener('sos:supabase-session',()=>{userId=null;load()});window.addEventListener('pageshow',load);setTimeout(load,1000);setTimeout(load,3000)}
window.SOS44OpenProfile=()=>{const panel=document.getElementById('profileStudio');if(!panel)return false;panel.hidden=false;panel.style.removeProperty('display');panel.scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>el('page')?.focus({preventScroll:true}),300);return true};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();