(()=>{'use strict';
const KEY='sos_font_size_preferences', clamp=x=>Math.min(250,Math.max(50,Math.round(Number(x)||100)));
let draft={text:100,nav:100},loadedFor='',dirty=false,loading=false;
const $=id=>document.getElementById('sos45-'+id);
function apply(){let r=document.documentElement;r.style.setProperty('--sos-text-scale',draft.text/100);r.style.setProperty('--sos-nav-scale',draft.nav/100);r.toggleAttribute('data-sos-text-scaled',draft.text!==100);r.toggleAttribute('data-sos-nav-scaled',draft.nav!==100);for(let [id,k] of [['page','text'],['nav','nav']]){if($(id))$(id).value=draft[k];if($(id+'-out'))$(id+'-out').textContent=draft[k]+'%';}}
function status(msg){if($('status'))$('status').textContent=msg}
function client(){return window.SOS_SUPABASE?.client||null}
async function load(){if(dirty||loading)return;const c=client();if(!c)return;loading=true;try{const {data,error}=await c.auth.getUser();if(error||!data?.user)return;if(loadedFor===data.user.id)return;loadedFor=data.user.id;const pref=data.user.user_metadata?.[KEY];draft={text:clamp(pref?.text??100),nav:clamp(pref?.nav??100)};apply();status('Preferences loaded from your Supabase account.')}catch(e){status('Could not load: '+e.message)}finally{loading=false}}
async function save(){const c=client();if(!c){status('Supabase client unavailable. Please sign in.');return}const b=$('save');b.disabled=true;status('Saving to Supabase…');try{const {data,error}=await c.auth.getUser();if(error||!data?.user)throw Error('Sign in to save font sizes.');const {error:saveError}=await c.auth.updateUser({data:{[KEY]:{text:draft.text,nav:draft.nav}}});if(saveError)throw saveError;dirty=false;loadedFor=data.user.id;status('Saved successfully to your Supabase account.')}catch(e){status('Save failed: '+e.message)}finally{b.disabled=false}}
function mount(){const font=document.querySelector('#publicProfileForm .memberAppearanceV7026');if(!font)return;const existing=$('studio');if(existing&&existing.parentElement===font)return;if(existing)existing.remove();const box=document.createElement('section');box.id='sos45-studio';box.className='sos45-studio';box.innerHTML=`<h4>Custom Font Size</h4><p>Drag each slider to preview text size. 100% is the original design.</p><div class="sos45-control"><label for="sos45-page">Website page text <output id="sos45-page-out">100%</output></label><input id="sos45-page" type="range" min="50" max="250" step="1" value="100"><div class="sos45-markers"><span>50% Small</span><span>100% Original</span><span>250% Large</span></div></div><div class="sos45-control"><label for="sos45-nav">Navigation text <output id="sos45-nav-out">100%</output></label><input id="sos45-nav" type="range" min="50" max="250" step="1" value="100"><div class="sos45-markers"><span>50% Small</span><span>100% Original</span><span>250% Large</span></div></div><div class="sos45-buttons"><button type="button" class="primaryButton" id="sos45-save">Save Font Sizes to Supabase</button><button type="button" class="secondaryButton" id="sos45-reset">Reset to 100%</button></div><p id="sos45-status" role="status" aria-live="polite">Choose your preferred sizes, then save.</p>`;
font.append(box);for(const [id,k] of [['page','text'],['nav','nav']])$(id).addEventListener('input',e=>{draft[k]=clamp(e.target.value);dirty=true;apply();status('Live preview — click Save to keep your changes.')});$('save').addEventListener('click',save);$('reset').addEventListener('click',()=>{draft={text:100,nav:100};dirty=true;apply();status('Default sizes previewed. Click Save to keep them.')});apply();load()}
function openProfile(){const host=document.getElementById('profileStudio');if(!host)return false;const nav=document.querySelector('[data-member-tab="profile"], [data-module="profile"], [data-member-module="profile"]');if(nav)nav.click();host.hidden=false;host.style.removeProperty('display');mount();host.scrollIntoView({behavior:'smooth',block:'start'});return true}
window.SOS44OpenProfile=openProfile;
function init(){mount();let queued=false;new MutationObserver(()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;const f=document.querySelector('#publicProfileForm .memberAppearanceV7026');if(f&&!$('studio'))mount()})}).observe(document.body,{subtree:true,childList:true});document.addEventListener('click',e=>{const a=e.target.closest('a[href="#profileStudio"],button[data-open-profile],a[data-open-profile]');if(a){e.preventDefault();openProfile()}},true);document.addEventListener('sos:supabase-session',load);window.addEventListener('pageshow',load);setTimeout(load,1200);setTimeout(load,3500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();