(()=>{'use strict';
const c=window.SOS_SUPABASE?.client,S=window.SOS;if(!c||!S?.K?.catalog)return;
const k=S.K.catalog,read=S.read.bind(S),write=S.write.bind(S),localBeforeCloud=read(S.K.catalog,[]);let cloud=[],ready=false,queue=Promise.resolve();
const status=t=>{const e=document.querySelector('#merchCloudStatus54');if(e)e.textContent=t;console.info('[Merch Cloud]',t)};
const reloadAdmin=()=>{if(!location.pathname.endsWith('/admin.html'))return;const b=document.querySelector('[data-panel="catalog"].active,[data-panel="catalog"][aria-selected="true"]');if(b)b.click()};
async function load(){const {data,error}=await c.from('sos_merch_products').select('id,product').order('updated_at',{ascending:true});if(error){status('Cloud catalog error: '+error.message+' · displaying saved merchandise');document.dispatchEvent(new CustomEvent('sos:merch-cloud-ready',{detail:read(k,[])}));return false}cloud=(data||[]).map(x=>x.product);ready=true;
 const local=read(k,[]);const ids=new Set(cloud.map(x=>String(x.id)));
 const missing=local.filter(x=>x&&x.id&&!ids.has(String(x.id)));
 const visible=cloud.length?[...cloud,...missing]:local;
 if(cloud.length)write(k,visible);
 document.dispatchEvent(new CustomEvent('sos:merch-cloud-ready',{detail:visible}));reloadAdmin();
 status(cloud.length+' cloud products loaded'+(missing.length?' · '+missing.length+' browser products ready to import':''));return true}
async function persist(items){const {data,error}=await c.auth.getUser();if(error||!data?.user)throw Error('Sign in as an administrator to save');const before=new Map(cloud.map(x=>[String(x.id),x])),after=new Map(items.map(x=>[String(x.id),x]));const changed=items.filter(x=>JSON.stringify(before.get(String(x.id)))!==JSON.stringify(x)),removed=cloud.filter(x=>!after.has(String(x.id)));if(changed.length){const res=await c.from('sos_merch_products').upsert(changed.map(x=>({id:String(x.id),product:x,updated_by:data.user.id,updated_at:new Date().toISOString()})),{onConflict:'id'});if(res.error)throw res.error}if(removed.length){const res=await c.from('sos_merch_products').delete().in('id',removed.map(x=>String(x.id)));if(res.error)throw res.error}cloud=items.map(x=>({...x}));status('Saved to Supabase')}
S.write=(key,value)=>{if(key!==k)return write(key,value);if(!ready){status('Waiting for Supabase catalog');return}write(key,value);queue=queue.catch(()=>{}).then(()=>persist(value)).catch(e=>{write(k,cloud);status('Save failed: '+e.message);reloadAdmin()})};
window.SOSMerchCloud={refresh:load,save:items=>{if(!ready)return Promise.reject(Error('Cloud not ready'));return persist(items)},ready:()=>ready};
if(location.pathname.endsWith('/admin.html')){const timer=setInterval(()=>{const form=document.querySelector('#catalogForm');if(!form)return;clearInterval(timer);if(document.querySelector('#merchCloudStatus54'))return;const e=document.createElement('p');e.id='merchCloudStatus54';e.setAttribute('role','status');e.className='adminLead';e.textContent='Loading Supabase merchandise…';form.before(e);const button=document.createElement('button');button.type='button';button.className='secondaryButton';button.textContent='Import previous browser products to Supabase';button.onclick=()=>{if(!ready)return status('Wait for catalog to load');const ids=new Set(cloud.map(x=>String(x.id)));const saved=read(k,[]);const candidates=[...localBeforeCloud,...saved];const missing=[...new Map(candidates.filter(x=>x&&x.id&&!ids.has(String(x.id))).map(x=>[String(x.id),x])).values()];if(!missing.length)return status('No new browser products to import');if(!confirm('Import '+missing.length+' products from this browser to Supabase?'))return;S.write(k,[...cloud,...missing]);setTimeout(reloadAdmin,700)};e.after(button)},150);setTimeout(()=>clearInterval(timer),15000)}
load();
})();