(()=>{'use strict';
const LESSONS=[
{level:'Beginner',type:'Official tutorial',title:'Getting Started in FL Studio',desc:'Learn the Channel Rack, Playlist, Mixer, Piano roll, recording and the basic beat-making workflow.',url:'https://www.youtube.com/watch?v=ort7ZLY-3zo',source:'FL Studio / Image-Line',tags:'beginner interface channel rack playlist mixer piano roll'},
{level:'Beginner',type:'Official manual',title:'FL Studio Getting Started',desc:'Official setup and first-steps learning hub for audio, MIDI, the interface and creating music.',url:'https://www.image-line.com/fl-studio-learning',source:'Image-Line',tags:'beginner setup audio midi manual'},
{level:'Plugins',type:'Official manual',title:'Installing VST, VST3 & CLAP Plugins',desc:'Official instructions for installing, scanning and using third-party plugins in FL Studio.',url:'https://www.image-line.com/fl-studio-learning/fl-studio-online-manual/html/basics_externalplugins.htm',source:'Image-Line',tags:'plugins vst vst3 clap install scan'},
{level:'Workflow',type:'Official manual',title:'FL Studio Online Manual',desc:'Search the complete official manual for the Playlist, Mixer, Piano roll, automation, recording and every native tool.',url:'https://www.image-line.com/fl-studio-learning/fl-studio-online-manual',source:'Image-Line',tags:'manual playlist mixer piano roll automation recording'},
{level:'Plugins',type:'Official tools',title:'FL Studio Plugins & Instruments',desc:'Explore Image-Line instruments and effects, then use the directory below to compare them with third-party tools.',url:'https://www.image-line.com/fl-studio/plugins',source:'Image-Line',tags:'native plugins instruments effects image line'},
{level:'Free',type:'Plugin directory',title:'KVR Free Instruments & Effects',desc:'Browse a large third-party directory of free music-production plugins. Verify compatibility and licensing before installing.',url:'https://www.kvraudio.com/plugins/instruments/effects/free/newest',source:'KVR Audio',tags:'free plugins vst effects instruments'},
{level:'Free',type:'Plugin guide',title:'Bedroom Producers Blog Free VST Guide',desc:'A practical discovery guide for free instruments and effects for music production.',url:'https://bedroomproducersblog.com/free-vst-plugins/',source:'Bedroom Producers Blog',tags:'free vst plugins effects synths'}
];
function mount(){const target=document.querySelector('.resourceToolbar');if(!target||document.querySelector('.producerLearning721'))return;const s=document.createElement('section');s.className='producerLearning721';s.innerHTML=`<div class="producerLearningHead721"><div><p class="sectionEyebrow">FL Studio Learning Center</p><h3>Learn the software. Understand the plugins. Build better tracks.</h3><p>Real learning resources from Image-Line and established plugin directories, organized inside the Producer Hub.</p></div><a class="secondaryButton" href="https://www.image-line.com/fl-studio-learning" target="_blank" rel="noopener">Official FL Studio Learning ↗</a></div><div class="learningTools721"><input id="learningSearch721" type="search" placeholder="Search tutorials: mixer, VST, Piano roll, recording…"><select id="learningLevel721"><option value="all">All learning</option>${[...new Set(LESSONS.map(x=>x.level))].map(x=>`<option>${x}</option>`).join('')}</select></div><div class="learningGrid721" id="learningGrid721"></div>`;target.insertAdjacentElement('beforebegin',s);const search=s.querySelector('#learningSearch721'),level=s.querySelector('#learningLevel721'),grid=s.querySelector('#learningGrid721');function draw(){const q=search.value.trim().toLowerCase(),l=level.value;const rows=LESSONS.filter(x=>(l==='all'||x.level===l)&&(!q||`${x.title} ${x.desc} ${x.tags} ${x.source}`.toLowerCase().includes(q)));grid.innerHTML=rows.map(x=>`<article class="learningCard721"><div class="learningMeta721"><span>${x.level}</span><small>${x.type}</small></div><h4>${x.title}</h4><p>${x.desc}</p><div class="learningSource721">Source: ${x.source}</div><a href="${x.url}" target="_blank" rel="noopener">Open tutorial / resource ↗</a></article>`).join('')||'<div class="producerNotice">No tutorial matches that search yet.</div>'}search.oninput=draw;level.onchange=draw;draw()}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',mount):mount();
})();
