import { serve } from "https://deno.land/std@0.224.0/http/server.ts";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}});
const env=(k:string)=>Deno.env.get(k)||"";
function catalog(){try{return JSON.parse(env("PAYMENT_CATALOG_JSON")||"{}")}catch{return {}}}
serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({error:"POST required"},405);
 try{const body=await req.json();const cat=catalog();if(body.action==="status")return json({stripe:!!env("STRIPE_SECRET_KEY"),paypal:!!(env("PAYPAL_CLIENT_ID")&&env("PAYPAL_CLIENT_SECRET")),catalog:Object.keys(cat).length>0});
 const provider=body.provider==="paypal"?"paypal":"stripe",items=Array.isArray(body.items)?body.items:[];if(!items.length)return json({error:"Cart is empty"},400);
 const lines=items.map((x:any)=>{const p=cat[String(x.id)];if(!p)throw new Error(`Unknown product: ${x.id}`);return{id:String(x.id),name:String(p.name||x.name||x.id),unit_amount:Number(p.unit_amount),currency:String(p.currency||"usd").toLowerCase(),qty:Math.max(1,Math.min(20,Number(x.qty)||1))}});const origin=String(body.origin||"").replace(/\/$/,"");
 if(provider==="stripe"){const key=env("STRIPE_SECRET_KEY");if(!key)return json({error:"Stripe is not configured"},503);const f=new URLSearchParams();f.set("mode","payment");f.set("success_url",`${origin}/merch.html?checkout=success`);f.set("cancel_url",`${origin}/merch.html?checkout=cancelled`);lines.forEach((l:any,i:number)=>{f.set(`line_items[${i}][price_data][currency]`,l.currency);f.set(`line_items[${i}][price_data][product_data][name]`,l.name);f.set(`line_items[${i}][price_data][unit_amount]`,String(l.unit_amount));f.set(`line_items[${i}][quantity]`,String(l.qty))});const r=await fetch("https://api.stripe.com/v1/checkout/sessions",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/x-www-form-urlencoded"},body:f});const d=await r.json();if(!r.ok)return json({error:d?.error?.message||"Stripe checkout failed"},502);return json({url:d.url})}
 const id=env("PAYPAL_CLIENT_ID"),secret=env("PAYPAL_CLIENT_SECRET"),base=env("PAYPAL_MODE")==="live"?"https://api-m.paypal.com":"https://api-m.sandbox.paypal.com";if(!id||!secret)return json({error:"PayPal is not configured"},503);const tokenRes=await fetch(`${base}/v1/oauth2/token`,{method:"POST",headers:{Authorization:`Basic ${btoa(`${id}:${secret}`)}`,"Content-Type":"application/x-www-form-urlencoded"},body:"grant_type=client_credentials"});const tok=await tokenRes.json();if(!tokenRes.ok)return json({error:"PayPal authentication failed"},502);const total=lines.reduce((s:any,l:any)=>s+l.unit_amount*l.qty,0);const orderRes=await fetch(`${base}/v2/checkout/orders`,{method:"POST",headers:{Authorization:`Bearer ${tok.access_token}`,"Content-Type":"application/json"},body:JSON.stringify({intent:"CAPTURE",purchase_units:[{amount:{currency_code:lines[0].currency.toUpperCase(),value:(total/100).toFixed(2)},description:lines.map((l:any)=>`${l.name} x${l.qty}`).join(", ").slice(0,127)}],application_context:{return_url:`${origin}/merch.html?checkout=success&provider=paypal`,cancel_url:`${origin}/merch.html?checkout=cancelled&provider=paypal`}})});const order=await orderRes.json();if(!orderRes.ok)return json({error:order?.message||"PayPal order failed"},502);return json({url:order.links?.find((x:any)=>x.rel==="approve")?.href})
 }catch(e){return json({error:e instanceof Error?e.message:"Checkout failed"},400)}});
